all : 
	gcc -o programaTrab *.c -g

run :
	./programaTrab

clean :
	rm *.o
	rm programaTrab
	clear
zip :
	zip programaTrab *.c *.h Makefile

remove :	
	rm arquivos/antes/*.bin

copy :
	cp arquivos/antes_copy/*.bin arquivos/antes/